#ifndef FRACTAL_BOX_CORE_ASSERT_LEVELS_HPP
#define FRACTAL_BOX_CORE_ASSERT_LEVELS_HPP

#define FR_ASSERT_LEVEL_AUTO (-1)
#define FR_ASSERT_LEVEL_NONE 0
#define FR_ASSERT_LEVEL_FAST 1
#define FR_ASSERT_LEVEL_DEFAULT 2
#define FR_ASSERT_LEVEL_AUDIT 3
#define FR_ASSERT_LEVEL_MAX FR_ASSERT_LEVEL_AUDIT

#endif // include guard
