#ifndef FRACTAL_BOX_CORE_LOG_LEVELS_HPP
#define FRACTAL_BOX_CORE_LOG_LEVELS_HPP

#define FR_LOG_LEVEL_AUTO (-1)
#define FR_LOG_LEVEL_NONE 0
#define FR_LOG_LEVEL_FATAL 1
#define FR_LOG_LEVEL_ERROR 2
#define FR_LOG_LEVEL_WARN 3
#define FR_LOG_LEVEL_INFO 4
#define FR_LOG_LEVEL_DEBUG 5
#define FR_LOG_LEVEL_TRACE 6
#define FR_LOG_LEVEL_MAX FR_LOG_LEVEL_TRACE

#endif // include guard
