#ifndef FRACTAL_BOX_PLATFORM_INPUT_NUM_CODES_HPP
#define FRACTAL_BOX_PLATFORM_INPUT_NUM_CODES_HPP

#include <limits>

#include <SDL3/SDL_keycode.h>
#include <SDL3/SDL_mouse.h>
#include <SDL3/SDL_scancode.h>

#include "fractal_box/core/enum_utils.hpp"
#include "fractal_box/core/int_types.hpp"

namespace fr {

/// @brief Integer value that represents a layout-independent phsycical key
///
/// @details This is just a type-safe one-to-one translation of SDL_Scancode, which itself is based
/// on USB standard
/// @note Identifier capitalization taken from https://docs.rs/sdl2/latest/sdl2/keyboard/enum.Scancode.html
/// @note Kp prefix means "keypad", a.k.a. "numpad" on most keyboards
enum class ScanCode: uint16_t {
	Unknown = SDL_SCANCODE_UNKNOWN,

	A = SDL_SCANCODE_A,
	B = SDL_SCANCODE_B,
	C = SDL_SCANCODE_C,
	D = SDL_SCANCODE_D,
	E = SDL_SCANCODE_E,
	F = SDL_SCANCODE_F,
	G = SDL_SCANCODE_G,
	H = SDL_SCANCODE_H,
	I = SDL_SCANCODE_I,
	J = SDL_SCANCODE_J,
	K = SDL_SCANCODE_K,
	L = SDL_SCANCODE_L,
	M = SDL_SCANCODE_M,
	N = SDL_SCANCODE_N,
	O = SDL_SCANCODE_O,
	P = SDL_SCANCODE_P,
	Q = SDL_SCANCODE_Q,
	R = SDL_SCANCODE_R,
	S = SDL_SCANCODE_S,
	T = SDL_SCANCODE_T,
	U = SDL_SCANCODE_U,
	V = SDL_SCANCODE_V,
	W = SDL_SCANCODE_W,
	X = SDL_SCANCODE_X,
	Y = SDL_SCANCODE_Y,
	Z = SDL_SCANCODE_Z,

	Digit1 = SDL_SCANCODE_1,
	Digit2 = SDL_SCANCODE_2,
	Digit3 = SDL_SCANCODE_3,
	Digit4 = SDL_SCANCODE_4,
	Digit5 = SDL_SCANCODE_5,
	Digit6 = SDL_SCANCODE_6,
	Digit7 = SDL_SCANCODE_7,
	Digit8 = SDL_SCANCODE_8,
	Digit9 = SDL_SCANCODE_9,
	Digit0 = SDL_SCANCODE_0,

	Return = SDL_SCANCODE_RETURN,
	Escape = SDL_SCANCODE_ESCAPE,
	Backspace = SDL_SCANCODE_BACKSPACE,
	Tab = SDL_SCANCODE_TAB,
	Space = SDL_SCANCODE_SPACE,

	Minus = SDL_SCANCODE_MINUS,
	Equals = SDL_SCANCODE_EQUALS,
	LeftBracket = SDL_SCANCODE_LEFTBRACKET,
	RightBracket = SDL_SCANCODE_RIGHTBRACKET,
	Backslash = SDL_SCANCODE_BACKSLASH,
	NonUsHash = SDL_SCANCODE_NONUSHASH,
	Semicolon = SDL_SCANCODE_SEMICOLON,
	Apostrophe = SDL_SCANCODE_APOSTROPHE,
	Grave = SDL_SCANCODE_GRAVE,
	Comma = SDL_SCANCODE_COMMA,
	Period = SDL_SCANCODE_PERIOD,
	Slash = SDL_SCANCODE_SLASH,

	CapsLock = SDL_SCANCODE_CAPSLOCK,

	F1 = SDL_SCANCODE_F1,
	F2 = SDL_SCANCODE_F2,
	F3 = SDL_SCANCODE_F3,
	F4 = SDL_SCANCODE_F4,
	F5 = SDL_SCANCODE_F5,
	F6 = SDL_SCANCODE_F6,
	F7 = SDL_SCANCODE_F7,
	F8 = SDL_SCANCODE_F8,
	F9 = SDL_SCANCODE_F9,
	F10 = SDL_SCANCODE_F10,
	F11 = SDL_SCANCODE_F11,
	F12 = SDL_SCANCODE_F12,

	PrintScreen = SDL_SCANCODE_PRINTSCREEN,
	ScrollLock = SDL_SCANCODE_SCROLLLOCK,
	Pause = SDL_SCANCODE_PAUSE,
	Insert = SDL_SCANCODE_INSERT,
	Home = SDL_SCANCODE_HOME,
	PageUp = SDL_SCANCODE_PAGEUP,
	Delete = SDL_SCANCODE_DELETE,
	End = SDL_SCANCODE_END,
	PageDown = SDL_SCANCODE_PAGEDOWN,
	Right = SDL_SCANCODE_RIGHT,
	Left = SDL_SCANCODE_LEFT,
	Down = SDL_SCANCODE_DOWN,
	Up = SDL_SCANCODE_UP,

	NumLockClear = SDL_SCANCODE_NUMLOCKCLEAR,
	KpDivide = SDL_SCANCODE_KP_DIVIDE,
	KpMultiply = SDL_SCANCODE_KP_MULTIPLY,
	KpMinus = SDL_SCANCODE_KP_MINUS,
	KpPlus = SDL_SCANCODE_KP_PLUS,
	KpEnter = SDL_SCANCODE_KP_ENTER,
	Kp1 = SDL_SCANCODE_KP_1,
	Kp2 = SDL_SCANCODE_KP_2,
	Kp3 = SDL_SCANCODE_KP_3,
	Kp4 = SDL_SCANCODE_KP_4,
	Kp5 = SDL_SCANCODE_KP_5,
	Kp6 = SDL_SCANCODE_KP_6,
	Kp7 = SDL_SCANCODE_KP_7,
	Kp8 = SDL_SCANCODE_KP_8,
	Kp9 = SDL_SCANCODE_KP_9,
	Kp0 = SDL_SCANCODE_KP_0,
	KpPeriod = SDL_SCANCODE_KP_PERIOD,

	NonUsBackslash = SDL_SCANCODE_NONUSBACKSLASH,
	Application = SDL_SCANCODE_APPLICATION,
	Power = SDL_SCANCODE_POWER,
	KpEquals = SDL_SCANCODE_KP_EQUALS,
	F13 = SDL_SCANCODE_F13,
	F14 = SDL_SCANCODE_F14,
	F15 = SDL_SCANCODE_F15,
	F16 = SDL_SCANCODE_F16,
	F17 = SDL_SCANCODE_F17,
	F18 = SDL_SCANCODE_F18,
	F19 = SDL_SCANCODE_F19,
	F20 = SDL_SCANCODE_F20,
	F21 = SDL_SCANCODE_F21,
	F22 = SDL_SCANCODE_F22,
	F23 = SDL_SCANCODE_F23,
	F24 = SDL_SCANCODE_F24,
	Execute = SDL_SCANCODE_EXECUTE,
	Help = SDL_SCANCODE_HELP,
	Menu = SDL_SCANCODE_MENU,
	Select = SDL_SCANCODE_SELECT,
	Stop = SDL_SCANCODE_STOP,
	Again = SDL_SCANCODE_AGAIN,
	Undo = SDL_SCANCODE_UNDO,
	Cut = SDL_SCANCODE_CUT,
	Copy = SDL_SCANCODE_COPY,
	Paste = SDL_SCANCODE_PASTE,
	Find = SDL_SCANCODE_FIND,
	Mute = SDL_SCANCODE_MUTE,
	VolumeUp = SDL_SCANCODE_VOLUMEUP,
	VolumeDown = SDL_SCANCODE_VOLUMEDOWN,

	KpComma = SDL_SCANCODE_KP_COMMA,
	KpEqualsAS400 = SDL_SCANCODE_KP_EQUALSAS400,

	International1 = SDL_SCANCODE_INTERNATIONAL1,
	International2 = SDL_SCANCODE_INTERNATIONAL2,
	International3 = SDL_SCANCODE_INTERNATIONAL3,
	International4 = SDL_SCANCODE_INTERNATIONAL4,
	International5 = SDL_SCANCODE_INTERNATIONAL5,
	International6 = SDL_SCANCODE_INTERNATIONAL6,
	International7 = SDL_SCANCODE_INTERNATIONAL7,
	International8 = SDL_SCANCODE_INTERNATIONAL8,
	International9 = SDL_SCANCODE_INTERNATIONAL9,
	Lang1 = SDL_SCANCODE_LANG1,
	Lang2 = SDL_SCANCODE_LANG2,
	Lang3 = SDL_SCANCODE_LANG3,
	Lang4 = SDL_SCANCODE_LANG4,
	Lang5 = SDL_SCANCODE_LANG5,
	Lang6 = SDL_SCANCODE_LANG6,
	Lang7 = SDL_SCANCODE_LANG7,
	Lang8 = SDL_SCANCODE_LANG8,
	Lang9 = SDL_SCANCODE_LANG9,

	AltErase = SDL_SCANCODE_ALTERASE,
	SysReq = SDL_SCANCODE_SYSREQ,
	Cancel = SDL_SCANCODE_CANCEL,
	Clear = SDL_SCANCODE_CLEAR,
	Prior = SDL_SCANCODE_PRIOR,
	Return2 = SDL_SCANCODE_RETURN2,
	Separator = SDL_SCANCODE_SEPARATOR,
	Out = SDL_SCANCODE_OUT,
	Oper = SDL_SCANCODE_OPER,
	ClearAgain = SDL_SCANCODE_CLEARAGAIN,
	CrSel = SDL_SCANCODE_CRSEL,
	ExSel = SDL_SCANCODE_EXSEL,

	Kp00 = SDL_SCANCODE_KP_00,
	Kp000 = SDL_SCANCODE_KP_000,
	ThousandsSeparator = SDL_SCANCODE_THOUSANDSSEPARATOR,
	DecimalSeparator = SDL_SCANCODE_DECIMALSEPARATOR,
	CurrencUunit = SDL_SCANCODE_CURRENCYUNIT,
	CurrencySubUnit = SDL_SCANCODE_CURRENCYSUBUNIT,
	KpLeftParen = SDL_SCANCODE_KP_LEFTPAREN,
	KpRightParen = SDL_SCANCODE_KP_RIGHTPAREN,
	KpLeftBrace = SDL_SCANCODE_KP_LEFTBRACE,
	KpRightBrace = SDL_SCANCODE_KP_RIGHTBRACE,
	KpTab = SDL_SCANCODE_KP_TAB,
	KpBackspace = SDL_SCANCODE_KP_BACKSPACE,
	KpA = SDL_SCANCODE_KP_A,
	KpB = SDL_SCANCODE_KP_B,
	KpC = SDL_SCANCODE_KP_C,
	KpD = SDL_SCANCODE_KP_D,
	KpE = SDL_SCANCODE_KP_E,
	KpF = SDL_SCANCODE_KP_F,
	KpXor = SDL_SCANCODE_KP_XOR,
	KpPower = SDL_SCANCODE_KP_POWER,
	KpPercent = SDL_SCANCODE_KP_PERCENT,
	KpLess = SDL_SCANCODE_KP_LESS,
	KpGreater = SDL_SCANCODE_KP_GREATER,
	KpAmpersand = SDL_SCANCODE_KP_AMPERSAND,
	KpDblAmpersand = SDL_SCANCODE_KP_DBLAMPERSAND,
	KpVerticalBar = SDL_SCANCODE_KP_VERTICALBAR,
	KpDblverticalBar = SDL_SCANCODE_KP_DBLVERTICALBAR,
	KpColon = SDL_SCANCODE_KP_COLON,
	KpHash = SDL_SCANCODE_KP_HASH,
	KpSpace = SDL_SCANCODE_KP_SPACE,
	KpAt = SDL_SCANCODE_KP_AT,
	KpExclam = SDL_SCANCODE_KP_EXCLAM,
	KpMemStore = SDL_SCANCODE_KP_MEMSTORE,
	KpMemRecall = SDL_SCANCODE_KP_MEMRECALL,
	KpMemClear = SDL_SCANCODE_KP_MEMCLEAR,
	KpMemAdd = SDL_SCANCODE_KP_MEMADD,
	KpMemSubtract = SDL_SCANCODE_KP_MEMSUBTRACT,
	KpMemMultiply = SDL_SCANCODE_KP_MEMMULTIPLY,
	KpMemDivide = SDL_SCANCODE_KP_MEMDIVIDE,
	KpPlusMinus = SDL_SCANCODE_KP_PLUSMINUS,
	KpClear = SDL_SCANCODE_KP_CLEAR,
	KpClearEntry = SDL_SCANCODE_KP_CLEARENTRY,
	KpBinary = SDL_SCANCODE_KP_BINARY,
	KpOctal = SDL_SCANCODE_KP_OCTAL,
	KpDecimal = SDL_SCANCODE_KP_DECIMAL,
	KpHexadecimal = SDL_SCANCODE_KP_HEXADECIMAL,

	LCtrl = SDL_SCANCODE_LCTRL,
	LShift = SDL_SCANCODE_LSHIFT,
	LAlt = SDL_SCANCODE_LALT,
	LGui = SDL_SCANCODE_LGUI,
	RCtrl = SDL_SCANCODE_RCTRL,
	RShift = SDL_SCANCODE_RSHIFT,
	RAlt = SDL_SCANCODE_RALT,
	RGui = SDL_SCANCODE_RGUI,

	Mode = SDL_SCANCODE_MODE,

	Sleep = SDL_SCANCODE_SLEEP,
	Wake = SDL_SCANCODE_WAKE,

	ChannelIncrement = SDL_SCANCODE_CHANNEL_INCREMENT,
	ChannelDecrement = SDL_SCANCODE_CHANNEL_DECREMENT,

	MediaPlay = SDL_SCANCODE_MEDIA_PLAY,
	MediaPause = SDL_SCANCODE_MEDIA_PAUSE,
	MediaRecord = SDL_SCANCODE_MEDIA_RECORD,
	MediaFastForward = SDL_SCANCODE_MEDIA_FAST_FORWARD,
	MediaRewind = SDL_SCANCODE_MEDIA_REWIND,
	MediaNextTrack = SDL_SCANCODE_MEDIA_NEXT_TRACK,
	MediaPreviousTrack = SDL_SCANCODE_MEDIA_PREVIOUS_TRACK,
	MediaStop = SDL_SCANCODE_MEDIA_STOP,
	MediaEject = SDL_SCANCODE_MEDIA_EJECT,
	MediaPlayPause = SDL_SCANCODE_MEDIA_PLAY_PAUSE,
	MediaSelect = SDL_SCANCODE_MEDIA_SELECT,

	AcNew = SDL_SCANCODE_AC_NEW,
	AcOpen = SDL_SCANCODE_AC_OPEN,
	AcClose = SDL_SCANCODE_AC_CLOSE,
	AcExit = SDL_SCANCODE_AC_EXIT,
	AcSave = SDL_SCANCODE_AC_SAVE,
	AcPrint = SDL_SCANCODE_AC_PRINT,
	AcProperties = SDL_SCANCODE_AC_PROPERTIES,

	AcSearch = SDL_SCANCODE_AC_SEARCH,
	AcHome = SDL_SCANCODE_AC_HOME,
	AcBack = SDL_SCANCODE_AC_BACK,
	AcForward = SDL_SCANCODE_AC_FORWARD,
	AcStop = SDL_SCANCODE_AC_STOP,
	AcRefresh = SDL_SCANCODE_AC_REFRESH,
	AcBookmarks = SDL_SCANCODE_AC_BOOKMARKS,

	SoftLeft = SDL_SCANCODE_SOFTLEFT,
	SoftRight = SDL_SCANCODE_SOFTRIGHT,
	Call = SDL_SCANCODE_CALL,
	EndCall = SDL_SCANCODE_ENDCALL,
};

inline constexpr auto num_scancodes = size_t{SDL_SCANCODE_COUNT};

/// @brief Integer value that represents a layout-specific virtual key. Unmodified unicode values
/// generated by key presses are stored as UTF-32 code points
///
/// @details This is just a type-safe one-to-one translation of SDL_KeyCode
/// on USB standard
/// @note Use SDL_TEXTINPUT/SDL_TEXTEDITING to properly handle text
enum class KeyCode: SDL_Keycode {
	Unknown = SDLK_UNKNOWN,

	Return = SDLK_RETURN,
	Escape = SDLK_ESCAPE,
	Backspace = SDLK_BACKSPACE,
	Tab = SDLK_TAB,
	Space = SDLK_SPACE,
	Exclaim = SDLK_EXCLAIM,
	DblApostrophe = SDLK_DBLAPOSTROPHE,
	Hash = SDLK_HASH,
	Dollar = SDLK_DOLLAR,
	Percent = SDLK_PERCENT,
	Ampersand = SDLK_AMPERSAND,
	Apostrophe = SDLK_APOSTROPHE,
	LeftParen = SDLK_LEFTPAREN,
	RightParen = SDLK_RIGHTPAREN,
	Asterisk = SDLK_ASTERISK,
	Plus = SDLK_PLUS,
	Comma = SDLK_COMMA,
	Minus = SDLK_MINUS,
	Period = SDLK_PERIOD,
	Slash = SDLK_SLASH,

	Digit0 = SDLK_0,
	Digit1 = SDLK_1,
	Digit2 = SDLK_2,
	Digit3 = SDLK_3,
	Digit4 = SDLK_4,
	Digit5 = SDLK_5,
	Digit6 = SDLK_6,
	Digit7 = SDLK_7,
	Digit8 = SDLK_8,
	Digit9 = SDLK_9,

	Colon = SDLK_COLON,
	Semicolon = SDLK_SEMICOLON,
	Less = SDLK_LESS,
	Equals = SDLK_EQUALS,
	Greater = SDLK_GREATER,
	Question = SDLK_QUESTION,
	At = SDLK_AT,

	LeftBracket = SDLK_LEFTBRACKET,
	Backslash = SDLK_BACKSLASH,
	RightBracket = SDLK_RIGHTBRACKET,
	Caret = SDLK_CARET,
	Underscore = SDLK_UNDERSCORE,
	Grave = SDLK_GRAVE,

	A = SDLK_A,
	B = SDLK_B,
	C = SDLK_C,
	D = SDLK_D,
	E = SDLK_E,
	F = SDLK_F,
	G = SDLK_G,
	H = SDLK_H,
	I = SDLK_I,
	J = SDLK_J,
	K = SDLK_K,
	L = SDLK_L,
	M = SDLK_M,
	N = SDLK_N,
	O = SDLK_O,
	P = SDLK_P,
	Q = SDLK_Q,
	R = SDLK_R,
	S = SDLK_S,
	T = SDLK_T,
	U = SDLK_U,
	V = SDLK_V,
	W = SDLK_W,
	X = SDLK_X,
	Y = SDLK_Y,
	Z = SDLK_Z,

	LeftBrace = SDLK_LEFTBRACE,
	Pipe = SDLK_PIPE,
	RightBrace = SDLK_RIGHTBRACE,
	Tilde = SDLK_TILDE,
	Delete = SDLK_DELETE,
	PlusMinus = SDLK_PLUSMINUS,
	CapsLock = SDLK_CAPSLOCK,

	F1 = SDLK_F1,
	F2 = SDLK_F2,
	F3 = SDLK_F3,
	F4 = SDLK_F4,
	F5 = SDLK_F5,
	F6 = SDLK_F6,
	F7 = SDLK_F7,
	F8 = SDLK_F8,
	F9 = SDLK_F9,
	F10 = SDLK_F10,
	F11 = SDLK_F11,
	F12 = SDLK_F12,

	PrintScreen = SDLK_PRINTSCREEN,
	ScrollLock = SDLK_SCROLLLOCK,
	Pause = SDLK_PAUSE,
	Insert = SDLK_INSERT,
	Home = SDLK_HOME,
	PageUp = SDLK_PAGEUP,
	End = SDLK_END,
	PageDown = SDLK_PAGEDOWN,
	Right = SDLK_RIGHT,
	Left = SDLK_LEFT,
	Down = SDLK_DOWN,
	Up = SDLK_UP,

	// NumPad keys
	// ^^^^^^^^^^^

	NumLockClear = SDLK_NUMLOCKCLEAR,
	KpDivide = SDLK_KP_DIVIDE,
	KpMultiply = SDLK_KP_MULTIPLY,
	KpMinus = SDLK_KP_MINUS,
	KpPlus = SDLK_KP_PLUS,
	KpEnter = SDLK_KP_ENTER,
	Kp1 = SDLK_KP_1,
	Kp2 = SDLK_KP_2,
	Kp3 = SDLK_KP_3,
	Kp4 = SDLK_KP_4,
	Kp5 = SDLK_KP_5,
	Kp6 = SDLK_KP_6,
	Kp7 = SDLK_KP_7,
	Kp8 = SDLK_KP_8,
	Kp9 = SDLK_KP_9,
	Kp0 = SDLK_KP_0,
	KpPeriod = SDLK_KP_PERIOD,

	Application = SDLK_APPLICATION,
	Power = SDLK_POWER,
	KpEquals = SDLK_KP_EQUALS,
	F13 = SDLK_F13,
	F14 = SDLK_F14,
	F15 = SDLK_F15,
	F16 = SDLK_F16,
	F17 = SDLK_F17,
	F18 = SDLK_F18,
	F19 = SDLK_F19,
	F20 = SDLK_F20,
	F21 = SDLK_F21,
	F22 = SDLK_F22,
	F23 = SDLK_F23,
	F24 = SDLK_F24,
	Execute = SDLK_EXECUTE,
	Help = SDLK_HELP,
	Menu = SDLK_MENU,
	Select = SDLK_SELECT,
	Stop = SDLK_STOP,
	Again = SDLK_AGAIN,
	Undo = SDLK_UNDO,
	Cut = SDLK_CUT,
	Copy = SDLK_COPY,
	Paste = SDLK_PASTE,
	Find = SDLK_FIND,
	Mute = SDLK_MUTE,
	VolumeUP = SDLK_VOLUMEUP,
	VolumeDown = SDLK_VOLUMEDOWN,
	KpComma = SDLK_KP_COMMA,
	KpEqualsAS400 = SDLK_KP_EQUALSAS400,

	AltErase = SDLK_ALTERASE,
	SysReq = SDLK_SYSREQ,
	Cancel = SDLK_CANCEL,
	Clear = SDLK_CLEAR,
	Prior = SDLK_PRIOR,
	Return2 = SDLK_RETURN2,
	Separator = SDLK_SEPARATOR,
	Out = SDLK_OUT,
	Oper = SDLK_OPER,
	ClearAgain = SDLK_CLEARAGAIN,
	Crsel = SDLK_CRSEL,
	Exsel = SDLK_EXSEL,

	Kp00 = SDLK_KP_00,
	Kp000 = SDLK_KP_000,
	ThousandsSeparator = SDLK_THOUSANDSSEPARATOR,

	DecimalSeparator = SDLK_DECIMALSEPARATOR,

	CurrencyUnit = SDLK_CURRENCYUNIT,
	CurrencySubUnit = SDLK_CURRENCYSUBUNIT,

	KpLeftParen = SDLK_KP_LEFTPAREN,
	KpRightParen = SDLK_KP_RIGHTPAREN,
	KpLeftBrace = SDLK_KP_LEFTBRACE,
	KpRightBrace = SDLK_KP_RIGHTBRACE,
	KpTab = SDLK_KP_TAB,
	KpBackspace = SDLK_KP_BACKSPACE,
	KpA = SDLK_KP_A,
	KpB = SDLK_KP_B,
	KpC = SDLK_KP_C,
	KpD = SDLK_KP_D,
	KpE = SDLK_KP_E,
	KpF = SDLK_KP_F,
	KpXor = SDLK_KP_XOR,
	KpPower = SDLK_KP_POWER,
	KpPercent = SDLK_KP_PERCENT,
	KpLess = SDLK_KP_LESS,
	KpGreater = SDLK_KP_GREATER,
	KpAmpersand = SDLK_KP_AMPERSAND,
	KpDblAmpersand = SDLK_KP_DBLAMPERSAND,

	KpVerticalBar = SDLK_KP_VERTICALBAR,
	KpDblverticalBar = SDLK_KP_DBLVERTICALBAR,

	KpColon = SDLK_KP_COLON,
	KpHash = SDLK_KP_HASH,
	KpSpace = SDLK_KP_SPACE,
	KpAt = SDLK_KP_AT,
	KpExclam = SDLK_KP_EXCLAM,
	KpMemStore = SDLK_KP_MEMSTORE,
	KpMemRecall = SDLK_KP_MEMRECALL,
	KpMemClear = SDLK_KP_MEMCLEAR,
	KpMemAdd = SDLK_KP_MEMADD,
	KpMemSubtract = SDLK_KP_MEMSUBTRACT,
	KpMemMultiply = SDLK_KP_MEMMULTIPLY,
	KpMemDivide = SDLK_KP_MEMDIVIDE,
	KpPlusMinus = SDLK_KP_PLUSMINUS,
	KpClear = SDLK_KP_CLEAR,
	KpClearEntry = SDLK_KP_CLEARENTRY,
	KpBinary = SDLK_KP_BINARY,
	KpOctal = SDLK_KP_OCTAL,
	KpDecimal = SDLK_KP_DECIMAL,
	KpHexadecimal = SDLK_KP_HEXADECIMAL,

	LCtrl = SDLK_LCTRL,
	LShift = SDLK_LSHIFT,
	LAlt = SDLK_LALT,
	LSuper = SDLK_LGUI,
	RCtrl = SDLK_RCTRL,
	RShift = SDLK_RSHIFT,
	RAlt = SDLK_RALT,
	RSuper = SDLK_RGUI,

	Mode = SDLK_MODE,

	Sleep = SDLK_SLEEP,
	Wake = SDLK_WAKE,
	ChannelIncrement = SDLK_CHANNEL_INCREMENT,
	ChannelDecrement = SDLK_CHANNEL_DECREMENT,

	MediaPlay = SDLK_MEDIA_PLAY,
	MediaPause = SDLK_MEDIA_PAUSE,
	MediaRecord = SDLK_MEDIA_RECORD,
	MediaFastForward = SDLK_MEDIA_FAST_FORWARD,
	MediaRewind = SDLK_MEDIA_REWIND,
	MediaNextTrack = SDLK_MEDIA_NEXT_TRACK,
	MediaPreviousTrack = SDLK_MEDIA_PREVIOUS_TRACK,
	MediaStop = SDLK_MEDIA_STOP,
	MediaEject = SDLK_MEDIA_EJECT,
	MediaPlayPause = SDLK_MEDIA_PLAY_PAUSE,
	MediaSelect = SDLK_MEDIA_SELECT,

	AcNew = SDLK_AC_NEW,
	AcOpen = SDLK_AC_OPEN,
	AcClose = SDLK_AC_CLOSE,
	AcExit = SDLK_AC_EXIT,
	AcSave = SDLK_AC_SAVE,
	AcPrint = SDLK_AC_PRINT,
	AcProperties = SDLK_AC_PROPERTIES,
	AcSearch = SDLK_AC_SEARCH,
	AcHome = SDLK_AC_HOME,
	AcBack = SDLK_AC_BACK,
	AcForward = SDLK_AC_FORWARD,
	AcStop = SDLK_AC_STOP,
	AcRefresh = SDLK_AC_REFRESH,
	AcBookmarks = SDLK_AC_BOOKMARKS,

	SoftLeft = SDLK_SOFTLEFT,
	SoftRight = SDLK_SOFTRIGHT,
	Call = SDLK_CALL,
	EndCall = SDLK_ENDCALL,
	LeftTab = SDLK_LEFT_TAB,
	Level5Shift = SDLK_LEVEL5_SHIFT,
	MultiKeyCompose = SDLK_MULTI_KEY_COMPOSE,

	LMeta = SDLK_LMETA,
	RMeta = SDLK_RMETA,
	LHyper = SDLK_LHYPER,
	RHyper = SDLK_RHYPER,
};

/// @brief Integer value that represents a key modifier
///
/// @details This is a type-safe one-to-one translation of SDL_Keymod
enum class KeyModifier: uint16_t {
	None = SDL_KMOD_NONE,
	LShift = SDL_KMOD_LSHIFT,
	RShift = SDL_KMOD_RSHIFT,
	Level5 = SDL_KMOD_LEVEL5,
	LCtrl = SDL_KMOD_LCTRL,
	RCtrl = SDL_KMOD_RCTRL,
	LAlt = SDL_KMOD_LALT,
	RAlt = SDL_KMOD_RALT,
	LSuper = SDL_KMOD_LGUI,
	RSuper = SDL_KMOD_RGUI,
	NumLock = SDL_KMOD_NUM,
	CapsLock = SDL_KMOD_CAPS,
	Mode = SDL_KMOD_MODE,
	ScrollLock = SDL_KMOD_SCROLL,
};

using KeyModifiers = Flags<KeyModifier>;

inline constexpr auto key_modifiers_ctrls = KeyModifiers{{KeyModifier::LCtrl, KeyModifier::RCtrl}};
static_assert(key_modifiers_ctrls.raw_value() == SDL_KMOD_CTRL);

inline constexpr auto key_modifiers_shifts = KeyModifiers{{KeyModifier::LShift,
	KeyModifier::RShift}};
static_assert(key_modifiers_shifts.raw_value() == SDL_KMOD_SHIFT);

inline constexpr auto key_modifiers_alts = KeyModifiers{{KeyModifier::LAlt, KeyModifier::RAlt}};
static_assert(key_modifiers_alts.raw_value() == SDL_KMOD_ALT);

inline constexpr auto key_modifiers_supers = KeyModifiers{{KeyModifier::LSuper,
	KeyModifier::RSuper}};
static_assert(key_modifiers_supers.raw_value() == SDL_KMOD_GUI);

enum class MouseWheelDirection: uint8_t {
	Normal = SDL_MOUSEWHEEL_NORMAL,
	Flipped = SDL_MOUSEWHEEL_FLIPPED,
};

enum class SystemCursor: uint8_t {
	Default = SDL_SYSTEM_CURSOR_DEFAULT,
	Text = SDL_SYSTEM_CURSOR_TEXT,
	Wait = SDL_SYSTEM_CURSOR_WAIT,
	Crosshair = SDL_SYSTEM_CURSOR_CROSSHAIR,
	Progress = SDL_SYSTEM_CURSOR_PROGRESS,
	/// Double arrow pointing northwest and southeast
	ResizeNWSE = SDL_SYSTEM_CURSOR_NWSE_RESIZE,
	/// Double arrow pointing northeast and southwest
	ResizeNESW = SDL_SYSTEM_CURSOR_NESW_RESIZE,
	/// Double arrow pointing west and east
	ResizeEW = SDL_SYSTEM_CURSOR_EW_RESIZE,
	/// Double arrow pointing north and south
	ResizeNS = SDL_SYSTEM_CURSOR_NS_RESIZE,
	/// Four pointed arrow pointing north, south, east, and west
	Move = SDL_SYSTEM_CURSOR_MOVE,
	/// Slashed circle or crossbones
	NotAllowed = SDL_SYSTEM_CURSOR_NOT_ALLOWED,
	Pointer = SDL_SYSTEM_CURSOR_POINTER,
	ResizeNW = SDL_SYSTEM_CURSOR_NW_RESIZE,
	ResizeN = SDL_SYSTEM_CURSOR_N_RESIZE,
	ResizeNE = SDL_SYSTEM_CURSOR_NE_RESIZE,
	ResizeE = SDL_SYSTEM_CURSOR_E_RESIZE,
	ResizeSE = SDL_SYSTEM_CURSOR_SE_RESIZE,
	ResizeS = SDL_SYSTEM_CURSOR_S_RESIZE,
	ResizeSw = SDL_SYSTEM_CURSOR_SW_RESIZE,
	ResizeW = SDL_SYSTEM_CURSOR_W_RESIZE,
};

inline constexpr auto num_system_cursors = size_t{SDL_SYSTEM_CURSOR_COUNT};

enum class MouseButton: uint8_t {
	Left = SDL_BUTTON_LEFT,
	Middle = SDL_BUTTON_MIDDLE,
	Right = SDL_BUTTON_RIGHT,
	X1 = SDL_BUTTON_X1,
	X2 = SDL_BUTTON_X2,
};

inline constexpr auto max_num_mouse_buttons
	= size_t{std::numeric_limits<std::underlying_type_t<MouseButton>>::max()};

enum class MouseButtonFlag: uint32_t {
	Left = SDL_BUTTON_LMASK,
	Middle = SDL_BUTTON_MMASK,
	Right = SDL_BUTTON_RMASK,
	X1 = SDL_BUTTON_X1MASK,
	X2 = SDL_BUTTON_X2MASK
};

using MouseButtonFlags = Flags<MouseButtonFlag>;

} // namespace fr
#endif // include guard
